### ISSUE TITLE
Controller cannot be used

### ISSUE THREAD

**Issue by SeoliteQ** [Salandora/SophisticatedStorage#1]
Created a new fabric instance (latest loader, 1.20.1) just to test this mod. Installed Sophisticated Core (Unofficial Fabric Port) and Modern KeyBinding [Fabric] - absolutely no other mods are installed.

The storage controller does not work. If I right click it with an item in my hand, it will not transfer said item to nearby storage items. 

No difference if I manually link the storage controller to the storages via the tool. The links are visible.

**Comment by SeoliteQ** [comment]
Thank you! Will the .jar be updated on curseforge accordingly or is there any way for myself to update it on my client?

**Comment by Salandora** [comment]
Hey yeah I'll soon release a new version, just testing a few fixes I did to make sure everything is okay.

If you want you could download the current development jars from here https://github.com/Salandora/SophisticatedMods/actions
Just keep in mind they can break your game if I made a mistake. 
So always make a backup before using them.

**Comment by SeoliteQ** [comment]
Many thanks, I managed to download the development jars as of your latest fix, but it came in a package of 9 different jars. So far I've tried three of the 0.58 versions but none allowed my game to boot. Unfortunately, modrinth doesn't provide me a succinct answer as to why it crashed either - logs simply end suddenly and crash logs aren't updated at all. Which .jar is the one I should actually try adding to my mods folder?

**Comment by Salandora** [comment]
Okay so first of all did you download the Artifacts for the right version? Check that the Branch is called ```1.20.1-fabric-dev```
After that in the zip folder you should find ```sophisticatedcore-0.5.108+mc1.20.1-SNAPSHOT-build.XX.jar``` and ```sophisticatedstorage-0.8.59+mc1.20.1-SNAPSHOT-build.XX.jar``` file. Where XX is a number.

**Comment by SeoliteQ** [comment]
Should have figured I needed to upgrade sophisticated core at the same time. I can confirm that storage, backpacks and core are working fine on my test world as well as my 395 mods world. Thank you for your patience!
