### ISSUE TITLE
Empty memorised slot voids transfered items

### ISSUE THREAD

**Issue by EugeneLagonski** [Salandora/SophisticatedStorage#12]
**Describe the bug**
when you have empty slots and they are all memorised inserting any other items voids them
(tried to reproduce it on the forge original, can't reproduce in the ATM9 modpack)

**To Reproduce**
1. fill all slots of a chest with any items
2. Press memorise all slots
3. Empty the first slot of the chest (it should be memorised still)
4. setup another inventory with items not memorised by the chest
5. connect them via any pipes (tested Modern Industrialisation and Industrial Revolution)
6. configure pushing from another inventory
7. see items disappear from another inventory but don't appear in the chest (as there are no slots for them in the chest)

**Expected behavior**
Items don't leave the inventory because they have no space for them.

**Screenshots**
Here is a screenshot with a chest with all memorised slots and the 1st slot is empty
![2024-06-16_22 42 10](https://github.com/Salandora/SophisticatedStorage/assets/22728161/cb424c11-4080-467f-8cac-12e4e9893269)

**Versions**
Minecraft version 1.20.1
Modpack All of Fabric: 2.3.0
Sophisticated Core: 0.5.109 build 99
Sophisticated Storage: 0.8.60 build 99

**Comment by Salandora** [comment]
Fixed in dev

**Comment by Salandora** [comment]
Included in the bugfix release from today.
