### ISSUE TITLE
Crash when upgrading chests / ticking entity

### ISSUE THREAD

**Issue by McBlob** [Salandora/SophisticatedStorage#15]
**Describe the bug**
Upgrading chests doesnt cause the upgrade item to dissappear
With the jade mod you can see in the chest preview, that the items sort of dissappear
if you try to open the chest you will get a ticking entity crash
[crash-2024-06-16_19.27.24-server.txt](https://github.com/user-attachments/files/15888794/crash-2024-06-16_19.27.24-server.txt)
A workaround is to grab the chest with the carry on mod and replacing the chest, in the jade preview the items will reappear and opening the chest won't crash the server anymore

**To Reproduce**
open server to lan
upgrade something like a gold chest to a diamond chest
upgrade item is still in the inventory
open chest
crash

**Versions**
1.20.1 fabric mod version build 99 so current newest version

**Comment by Salandora** [comment]
Yes this is a bug in the builds 97-99.
It's also the reason for the big warning in the mod description.
Yesterday I pushed a fix for it, but still need to verify that nothing else broke by that fix.

**Comment by Salandora** [comment]
Fix is out.
