### ISSUE TITLE
Chests not combining into a double chest when placed by each other.

### ISSUE THREAD

**Issue by NaterTheTater** [Salandora/SophisticatedStorage#19]
When I place two chests next to each other they do not combine into a double chest. Nether placing on the gound beside each other or crouching and right clicking on the side of the chest to place it. I am on version  sophisticatedstorage-0.8.60+mc1.20.1-SNAPSHOT-build.104.jar
![Double Chest Sophisticated Storage Fabric](https://github.com/Salandora/SophisticatedStorage/assets/174115583/0c1a2488-c697-4899-b170-f8c3f1c94dde)

**Comment by Salandora** [comment]
Yes this is correct as it is not in the current version, it will get added in the next update tho
