### ISSUE TITLE
Item Dupe with Limited Barrels and Storage Controller

### ISSUE THREAD

**Issue by j00w33** [Salandora/SophisticatedStorage#2]
**Describe the bug**

Piping into a storage controller with empty barrels will continue filling up the barrels with the source contents without depleting the source contents

After you trigger this on empty barrels, the barrels are no longer empty. Removing and readding the items to the chest will continue the glitch, until the barrels are at max count  
Also with no empty slots. If you break and replace the connecting pipe the glitch will resolve itself. -- The pipe broken doesn't have to be directly touching the storage controller.

Tested with different barrels (I, II, III, IIII). Limited barrels are the only ones that function this way, normal barrels and chests do not.

*I'm using AOF7 modpack with Industrial Revolution Item Pipes*

**To Reproduce**
1. Place a storage controller
2. Place empty limited barrels around the controller
3. connect a chest to the controller using an IndRev pipe and servo
4. Place items in the chest
5. Watch as items stay in chest but the barrels fill to max capacity.

**Expected behavior**
Items move into limited barrels without being left behind in a chest

**Screenshots**

[Example Video](https://cdn.discordapp.com/attachments/1137454902625443840/1239675081920352328/Peek_2024-05-13_16-25.webm?ex=6643c8e3&is=66427763&hm=c464c5dfc4f03f71bfb09c3084620ae9487c3c27d9dc2cf27a08b904a91ab37c&)

**Versions**
**Sophisticated Core:** 0.5.108+mc1.20.1-build.39
**Sophisticated Storage:** 0.8.59+mc1.20.1-build.39
**Sophisticated Backpacks:** 3.19.4+mc1.20.1-build.39

**Comment by Salandora** [comment]
Just tested to be sure (with Industrial Revolution), this is fixed in the current bugfix version I'm working on.
Thank you for reporting.
