### ISSUE TITLE
Item Dupe with unstackable items

### ISSUE THREAD

**Issue by King0fgames** [Salandora/SophisticatedStorage#20]
**Describe the bug**
Unstackable like items are duplicated when put into storage controller

**To Reproduce**
1. Set storage controller next to chest, unenchanted diamond pickaxe inside chest
2. Right click storage controller with enchanted diamond pickaxe
3. Result: enchanted diamond pick is not removed from inventory but duplicated into chest

**Expected behavior**
Enchanted pick is deposited

**Screenshots**
![Base Profile Screenshot 2024 07 02 - 21 43 56 75](https://github.com/Salandora/SophisticatedStorage/assets/22490079/f2d6ebe6-035f-4521-9eec-b49c00a8a3bd)

**Versions**
v0.8.60 build.104

**Comment by Salandora** [comment]
Can confirm this as a bug, will look into why it's happening.
Thanks for reporting.

**Comment by Salandora** [comment]
Fixed in sophisticatedcores dev-feature-update

**Comment by Salandora** [comment]
New release is out, this should now be fixed.
