### ISSUE TITLE
Crashes with Storage Bus (from AE2) on a Limited Barrel + Compression Upgrade

### ISSUE THREAD

**Issue by asrieldashie** [Salandora/SophisticatedStorage#21]
**Describe the bug**
The world crashes when trying to attach a Storage Bus (regardless if it's online) to any Limited Barrel with Compression Upgrade installed and have items inside.

[Logs](https://mclo.gs/58eM79l)

**To Reproduce**
1. Place any Limited Barrel and install Compression Upgrade
2. Insert items
3. Attach the Storage Bus on it

**Expected behavior**
The world doesn't crash

**Screenshots**
-

**Versions**
Storage 0.8.60, Core 0.5.109
Minecraft 1.20.1, Fabric 0.15.11

**Comment by Salandora** [comment]
Duplicate of #16
