### ISSUE TITLE
Server hard crash on 1.20.1 when hopper and compacting upgrades are used

### ISSUE THREAD

**Issue by WindClan** [Salandora/SophisticatedStorage#23]
[just-the-crash.txt](https://github.com/user-attachments/files/16723445/just-the-crash.txt)
I don't know the exact circumstances besides the upgrades (and the crash log) but it seems to be related to the hopper upgrade

**Comment by WindClan** [comment]
More info: It was a barrel used in a gold farm that apparently had the compacting info (crash log just said hopper upgrade tick error) which seems related to #16 but unlike that crash, it happens 100% of the time

**Comment by scmcgowen** [comment]
[r.-2.-2.mca.zip](https://github.com/user-attachments/files/16733594/r.-2.-2.mca.zip)
Here is the Minecraft Region file from the server where it happened. The coordinates are at -976 245 -910

**Comment by scmcgowen** [comment]
Here is the Minecraft Region file from the server where it happened. The coordinates are at -976 245 -910
[r.-2.-2.mca.zip](https://github.com/user-attachments/files/16733641/r.-2.-2.mca.zip)
This time its in the correct dimension

**Comment by WindClan** [comment]
It could have also been the compression upgrade

**Comment by Salandora** [comment]
Yeah I believe this to be a duplicate of #16 too.
Which means it should be fixed in fabric-dev-feature-update. 
Will test it with your region file, before closing this issue.

**Comment by Salandora** [comment]
Should be fixed, please comment here if you still have issues with it.
