### ISSUE TITLE
Duplication Bug when using BeansBackpack Mod

### ISSUE THREAD

**Issue by fr4nk3n5731n** [Salandora/SophisticatedStorage#24]
**Describe the bug**

When using Sophisticated Storage along with Beans Backpack it is possible to duplicate items when wearing a cauldron on the back. I'm not entirely sure if this is a SophisticatedStorage or Beans Backpack bug.

**To Reproduce**
1. Equip cauldron on back
2. Put >=2 stackable items into Limited Barrel (works with any type of limited barrel)
3. left click barrel
5. you will now have 1 item in your inventory and dropped 1 item on the floor
7. can be combined with Pickup Module to generate lots of items quickly

This works on both single player and multiplayer.

**Expected behavior**
I'd expect Sophisticated Storage to not drop items on the floor and also add them to the player inventory when having a cauldron on the back.

**Screenshots**
Cauldron on Back:

https://github.com/user-attachments/assets/f6aabe6c-84fb-4bb7-b9c9-20514257efbe

Cauldron on Back + Pickup Module:

https://github.com/user-attachments/assets/5b8d3c77-ba00-4fed-8899-53710e8d3285

Backpack on Back:

https://github.com/user-attachments/assets/169b5b40-9c57-406d-94b6-7cb90c4f0025

**Versions**
- Minecraft: 1.20.1
- Fabric: 15.11
- SophisticatedStorage: 0.8.60+mc1.20.1-SNAPSHOT-build.104
- SophisticatedStorage Core: 0.5.109+mc1.20.1-SNAPSHOT-build.104
- BeansBackpack: [fabric-1.20.1-2.0.2](https://modrinth.com/mod/beans-backpacks/version/20.1-2.0.2)
- Fabric API: [0.92.2+1.20.1](https://modrinth.com/mod/fabric-api/version/0.92.2+1.20.1)

**Comment by Salandora** [comment]
Found and fixed in fabric-dev-feature-update

**Comment by Salandora** [comment]
New release is out, this should now be fixed.
