### ISSUE TITLE
Punching Item in Limited Barrel while in creative mode Crashes server

### ISSUE THREAD

**Issue by j00w33** [Salandora/SophisticatedStorage#3]
**Describe the bug**
While in creative mode punching a limited barrel to extract an item causes server to crash  
This only happens on a server, Singleplayer works fine

[Crash Log](https://pastebin.com/a43wrjkM)

**To Reproduce**
1. Be in creative mode on server
2. Have limited barrel with items in it.
3. punch limited barrels to receive the item
4. full stop server

**Expected behavior**
In singleplayer, the behavior gives me the item that's in the barrel

**Versions**
**Sophisticated Core:** 0.5.108+mc1.20.1-build.39
**Sophisticated Storage:** 0.8.59+mc1.20.1-build.39
**Sophisticated Backpacks:** 3.19.4+mc1.20.1-build.39

**Comment by Salandora** [comment]
Found the bug and will be fixed in current bugfix version.
Thank you for reporting.
