### ISSUE TITLE
Item lost if not currently stocked

### ISSUE THREAD

**Issue by Redoishi** [Salandora/SophisticatedStorage#31]
**Describe the bug**
If, with a hopper, an item not present in the system is fed into the storage controller, the item is lost.

**To Reproduce**
1. Add storage container
2. Add storage controller and hopper
3. Input an item that is not currently in stock
4. Item lost

(Same with AE2)

**Versions**
sophisticatedstorage-1.20.1-0.10.44.23

**Comment by Salandora** [comment]
Will be fixed in next update.

**Comment by Salandora** [comment]
New Sophisticated Core and Storage are out and should fix the issue.
