### ISSUE TITLE
Possible conflict with Tom's Simple Storage

### ISSUE THREAD

**Issue by Gamerbolts** [Salandora/SophisticatedStorage#32]
Hello, I created a modpack (PXC Cobblemon) and have a server running. I have a user reporting an issue and possible conflict with the Sophisticated Storage mod. They hooked up a Tom's Simple Storage interface on a Sophisticated Storage Controller which caused all of the items they put it to delete. Not sure who's mod it could be so sending to both githubs :)

Install the PXC Cobblemon modpack
Hook up a Tom's Simple Storage interface to a Sophisticated Storage Controller
Place items in and they get deleted

**Expected behavior**
Items to go into the inventory

Modpack: PXC Cobblemon
Fabric 1.20.1
Fabric 0.16.5
Sophisticated Storage 0.10.44.23

**Comment by Salandora** [comment]
Did they have any chests around the controller? 
Would be good if you can make a screenshot of a contraption with that issue

**Comment by Salandora** [comment]
Also sounds related to #31

**Comment by Salandora** [comment]
Can confirm it's the same bug as in #31 therefore closing this one.
Will be fixed in next update.

**Comment by Gamerbolts** [comment]
Sounds good. Thanks! Sorry for the dupe post

**Comment by IranMine123** [comment]
hey @Salandora i think this issue should be reopened cuz there is another bug about it
it is the same as GamerBolts said but instead it freeze the game and then crash it.
I'm using 1.21.1-0.10.52.54.
as it shows it works with sophi' storages but not with tom's storages.

Here's the video:

https://github.com/user-attachments/assets/bf5c6b3b-180f-44a6-94bc-49ae7a196ac9

**Comment by Salandora** [comment]
Do you have a crash log for that?
I'll try to replicate the issue.

**Comment by IranMine123** [comment]
> Do you have a crash log for that?
I'll try to replicate the issue.

No, nothing in logs.

------------

there is one more bug.
so i tried using sophi's barrels. i can't put back the items i picked up from terminal. for this one i have the error log. (btw it does'nt crash/freeze the game)
error: https://mclo.gs/CJzqLRU

https://github.com/user-attachments/assets/16f6af56-188d-4f4d-859a-c1fd7797b5cc

**Comment by Salandora** [comment]
Okay no worries.
The crash log you posted is a known bug, it was an oversight when I drastically changed the code base to be more compatible with the original again. It's fixed in dev, was planning to release that this weekend, guess I have to fix some more before that now.

**Comment by IranMine123** [comment]
ok. btw sorry about messing with ur time and code😭
i think i reported too many issues this week
tell us if you need help with the issues

**Comment by Salandora** [comment]
Don't worry, I'm glad they get reported, and if I would have done a better job testing everything I wouldn't have as much work now as I do.
So if you find bugs please don't be afraid to open a report, it's for the benefit of everyone :)

**Comment by Salandora** [comment]
Found out why the game was freezing.

**Comment by Salandora** [comment]
New release is out, this should now be fixed.
