### ISSUE TITLE
Storage Tool Mode Switching - not working

### ISSUE THREAD

**Issue by gvancamp** [Salandora/SophisticatedStorage#39]
If I understand correctly, the storage tool should change modes when you sneak + use mouse scroll wheel while holding the tool.

I tried that, but the hotbar just moves to the next/previous slot (normal scroll behavior) rather than switch tool modes.

This is on Fabric 0.16.9-1.21.1

**Comment by Salandora** [comment]
Found the issue will be fixed in the new update.

**Comment by Salandora** [comment]
New release is out, this should now be fixed.
