### ISSUE TITLE
The backpack models and some of the barrel and chest models are invisible

### ISSUE THREAD

**Issue by KuschelKaktus88** [Salandora/SophisticatedStorage#4]
**Describe the bug**
so before it always worked but, today i strted minecraft and the item tab icons are invisible and most of the models exept for the upgrades

**Versions**
newest versions of soph. bp, soph. core and sophh. storage

**Comment by Salandora** [comment]
Did you update any mods or installed new ones?

**Comment by KuschelKaktus88** [comment]
nvm, accidentally hit the update all button 2 hours ago. yeah the pack doesnt start anymore so nvm
