### ISSUE TITLE
Crash when hopper moves item into Sophisticated Barrel

### ISSUE THREAD

**Issue by legomaniac89** [Salandora/SophisticatedStorage#40]
**Describe the bug**
When a hopper transfers an item into a container from this mod, the game crashes.

**To Reproduce**
1. connect hopper to container
2. place item in hopper
4. game crashes

**Expected behavior**
Hopper should transfer item without crashing

**Screenshots**
n/a

**Versions**
Storage: 1.21.1-0.10.52.54
Core: 1.21.1-0.6.50.61
Fabric API: 0.109.0+1.21.1

**Comment by legomaniac89** [comment]
full crash report: https://file.io/aMZcRsGQD1Xx

**Comment by legomaniac89** [comment]
full crash log: https://jmp.sh/s/wDTXVjoFIuwhxnQk7TX1

this crash is also repeatable with a hopper into a Sophisticated Backpack

**Comment by IranMine123** [comment]
same as Storage Controller. (_I just lose my World ;-;_)
crash log: https://mclo.gs/kLiFnhA

**Comment by Salandora** [comment]
New release is out, this should now be fixed.
With the new update your worlds should load again.
