### ISSUE TITLE
interaction bug between storage controller and storage link with the create mod funnels

### ISSUE THREAD

**Issue by Sparroww69** [Salandora/SophisticatedStorage#5]
**Describe the bug**
if i throw an item on the funnel facing into the controller that is linked to the storage link placed on a container, item just will go into the container until its full

**To Reproduce**
1. install the create mod
2. place a container from sophisticated storage mod
3. place a storage link onto the container
4. place a storage controller nearby
5. link the controller to the link using the storage tool
6. place a brass funnel on the controller, make sure that the arrow on the funnel is facing into the controller (you can change it by right clicking with a wrench)
7. throw an item on the funnel
8. open the container and observe the dupe

**Expected behavior**
item should just go into the container without duping, and if i link the storage controller directly to the container without using the link it works just fine

**Screens**
![2024-05-18_16 08 10](https://github.com/Salandora/SophisticatedStorage/assets/139510787/81de29f1-129b-46d7-ace5-ff09ec28e922) the dupe result (i removed some of the sand)
![2024-05-18_16 10 56](https://github.com/Salandora/SophisticatedStorage/assets/139510787/e58aa8d0-f3a6-4010-b0c6-74aa9155199a) the duping contraption

**Versions**
Create 1.20.1 v0.5.1.f Patch 1
Sophisticated Storage 0.8.59+mc1.20.1-build.39

**Comment by Salandora** [comment]
Hey,

that is a known bug (#2) it's fixed in dev and will be included in the upcoming bugfix release.

**Comment by Salandora** [comment]
New release with bugfix on CF and Modrinth
