### ISSUE TITLE
Void Upgrade not working and causing crash

### ISSUE THREAD

**Issue by schz404** [Salandora/SophisticatedStorage#7]
I was building an enderman farm, I placed a chest with magnet + void (for enderpearls) when placing enderpearls in the filter or taking out enderpearls of the chest the game crashes.

Crash report:
[crashST.txt](https://github.com/Salandora/SophisticatedStorage/files/15472939/crashST.txt)

**To Reproduce**
1. Open chest
2. Void settings: Works with GUI/ Void any/ Block enderpearls
3. Place enderpearls in/ take enderpearls out
4. Crash

Minecraft 1.20.1 Modrinth
Sophisticated Backpacks 3.19.5+mc1.20.1-build.76
Sophisticated Core 0.5.109+mc1.20.1-build.76
Sophisticated Storage 0.8.60+mc1.20.1-build.76

**Comment by Salandora** [comment]
Just looked at the code and yeah I can see why it's happening.
