### ISSUE TITLE
Texture for Sophisticated Storage Barrels is defaulting to sophisticatedstorage:crimson_barrel texture

### ISSUE THREAD

**Issue by thethisthat** [Salandora/SophisticatedStorage#8]
When placing or upgrading sophisticated barrels in the world, all sophisticated barrels are using the crimson barrel texture. Chests and shulker boxes do not appear to be affected. All functionality in the GUI of the barrels is as expected. However, the item display feature does not appear to be working as the texture is defaulting to a crimson barrel. Also, the textures are correct within the creative menu and JEI menu. They only default to the crimson barrel when placed in the world. This happens on any barrel with any level of upgrade. The texture is correct for the item when held in the player hand and in the player inventory as well.

1. Use a basic upgrade on a vanilla barrel or place a sophisticated barrel in the world.
2. Observe that the barrel has the crimson barrel texture.

**Troubleshooting**
-Removed all shader packs
-Removed all resource packs
-Confirmed version matches fabric and game versions

**Expected behavior**
The barrel should use the texture of the sophisticated barrel corresponding to wood type, upgrade tier, and item display feature.

**Screenshots**
![image](https://github.com/Salandora/SophisticatedStorage/assets/122894663/dc57aee6-c91b-463e-8421-af8474061518)

**Versions**
sophisticatedstorage-0.8.60+mc1.20.1-SNAPSHOT-build.76

**Comment by thethisthat** [comment]
Further testing revealed that this may be a conflict with Sodium version: sodium-fabric-0.5.8+mc1.20.1

**Comment by Salandora** [comment]
Do you have Indium installed?
If not please add Indium and let me know if it still happens.

**Comment by thethisthat** [comment]
Thanks for writing back. I have installed Indium and the issue looks to be resolved. I apologize for not knowing Indium was needed when using Sodium. Thanks again!

**Comment by Salandora** [comment]
No need to apologize.
I should probably include a warning that pops up when sodium is detected without indium.
